### ISSUE TITLE
Any progress on the release?

### ISSUE THREAD

**Issue by manikantag** [brettwooldridge/HikariJSON#1]

**Comment by brettwooldridge** [comment]
I've been focused on the latest release of HikariCP, but now that is complete, so I hope to turn my attention to HikariJSON for a while.

**Comment by nosideeffects** [comment]
Just wondering if you were likely to return to this project sometime in 2017. A bulk of our application time is now spent in Serialization/Deserialization and I would love to put all your hard work to good use.
