### ISSUE TITLE
Project progress

### ISSUE THREAD

**Issue by mballoni** [brettwooldridge/HikariJSON#3]
I just found this project throught the HikariCP (congratulations, by the way).
 I was wondering if there are any plans on taking back on this project and what else is planned, in case the first answer is yes.
 Thank you !!!

**Comment by brettwooldridge** [comment]
@mballoni I would love to invest more time in this project, but unfortunately work, HikariCP, and other side-projects such as [improved Kotlin compiler support](https://github.com/brettwooldridge/buck/commits/kotlin-compiler2) in [Buck](https://buckbuild.com) have been occupying my time.

**Comment by mballoni** [comment]
@brettwooldridge I understand.
Are there any feature roadmap for this project? I would love to play around with it. It's been kind of an open source collaboration trainning for me.
 Thank you very much for your attention.

**Comment by brettwooldridge** [comment]
Headed off to bed, I'll give you some of my plans tomorrow.

**Comment by mballoni** [comment]
Awesome, thank you for your attention.

**Comment by brettwooldridge** [comment]
#4
